export { default as Navbar } from '../Globals/Navbar';
export { default as Footer } from '../Globals/Footer';
export { default as SharedLayout } from '../Globals/SharedLayout';
export { default as Hero } from './Home/Hero';
export { default as CaseStudy } from '../Components/Home/CaseStudy'
export { default as CaseStudyData } from './Data/CaseStudyData'
export { default as CaseStudyDetails } from '../Pages/CaseStudyDetails'
export { default as Services } from './Home/Services/Services'
export { default as Services2 } from './Home/Services/Services2'
export { default as ServicesSection } from './Home/Services/ServiceSection'
export { default as Services3 } from './Home/Services/Services3'
export { default as PricingTable } from './Home/PricingTable'
export { default as Contact } from '../Pages/Contact'
export { default as Signup } from './Home/Klaviyo/Signup'
export { default as CollectWebsiteURL } from '../Pages/Klaviyo/CollectWebsiteURL'
export { default as GetWebsite } from '../Pages/GetWebsite'
export { default as Cookies } from '../Pages/Policies/Cookies'
export { default as Terms } from '../Pages/Policies/Terms'
export { default as Privacy } from '../Pages/Policies/Privacy'
